export const FORAGER_AUTH_DATA = "FORAGER_AUTH_DATA";
export const FORAGER_USER_DATA = "FORAGER_USER_DATA";
export const FORAGER_AGENCY_DATA = "FORAGER_AGENCY_DATA";

export const PREVIOUS_ROUTE_QUERY_KEY = "rt";

export const ROUTE_CHANGE_EVENT = "ROUTE_CHANGE_EVENT";
